language: node_js
node_js:
    - lts/*
script:
    - yarn build
    - yarn test
deploy:
    - provider: script
      skip_cleanup: true
      script:
          - npx @dhis2/cli utils release --publish npm
      on:
          tags: false
          branch: master
env:
    global:
        - GIT_AUTHOR_NAME=@dhis2-bot
        - GIT_AUTHOR_EMAIL=apps@dhis2.org
        - GIT_COMMITTER_NAME=@dhis2-bot
        - GIT_COMMITTER_EMAIL=apps@dhis2.org
        - secure: kCM2qSE77q2YbE6tvsl3NXnE58oT1Qt7xtqbnnu2YWpe3XAhE66zoSgqN7IQdKs7UMYHoX7IUZnsrUSJeWcha3309MeLMNCM0k/b4yXoEqTRfQFbU1dF4brLkxpEB4I1LFQE0T0qUemZqojGr6NY+gp3qPB4bjbl9g1NU+N0OTW6wmECyvGIvDpJFHoD25Dsgwj3PzxguqTtCE06peczdIckUhk2GqVrv0nMadfmkF8RiIgUTcp+BzdsUlOpZpNJOruPg5BdF4SMfu/puudH2+Cs1jh7E8zjm5m6VTDsOGHCJ9K5vCY5nbU2epCiGzwBw3NpPWOAiFJwC3x59KnVRpX0hxsT3s1gbvqLP0G5fRhrXVf4Kk5Ty7uh9GDOP/e0FJEOqW7ZERz/FPMO1N0RuneDjSYtQF20XGO3qsjajXqBdlIZVRLhaz9g1M+U5eErYwOr15QR/fIOJLMlvMbxBIQFYM8PSrbiNBpR7wTuIPkBh0zNXTqcXg1Ai2zBTy15D0vRanSwty8owSgiBJHA5pvlWD1VmCN4Lt7oUAmJY2EwH9jXgHhNBdWtR0JevRjLhdTZ0EZE2QNflEsrwAFxIhx10FrhPfR8k7HsD86B1TbSzPOgHnxokv8EQQ9FMPe960DGE+c+qCVrLd3BRUY+FvrIcWBeDSuqvKK/QFVUGSc=
        - secure: Py72yaovVBT1dJVdPhMLolEN+BHPF4U3uRkanJl8BtzIXXK0qxE6OvicjO6xxhxvajX5aLpN6wZnjXMdQZRO37AZJ3rjkYtklJToD+A6IowPrbqy5vdEYf2Uq89AQwp5jga+uFfQFi2TVuamTppSp8OJ6yYVCVhhEnbfQJ4U9bscvn+3HjS5r3r968067lzEPcp2ANFJQxtpsH38CvFZJMGGGlFXE/XKhd3ubpwxVD77OGkCBYrZdWhf1hE8w3rQcyFikGO82+BeT/MDyrdASk+UoJqY+KW+9pciKWeWKSKEOi8Dp/m5oals8pI3NAxLB9w6KkVLBVFwMmvMBW5MRZxNXOB7vf0AiZAnCSHaUBRMWQLRLIeJYrcK+0RQhqHVE1k4UIVbHJOvI02pnvhE/SUI1KqZ2nBI6wNgF2DCXzv6U4cbSuKOfOlJVo2VGqFdK3FtlF/+TT2WbDE+fXpU9eicE5wFREeZldE1jIuFFq+tfbe/W4Yf3lmLrciWFzWglGHIevj8tJAW6smoRsq39MOLN0fRAt4t/cRpzN0HKaY+q6ZvdqJTdZzJDnrF+N8R3ol1AoAGJD3I6rpdpfM95vxCMLmD23WksyqIak1RcLyVkx2vK5DGOMLxvnus0zenOQKhvgfud2eisQRzsao/mLJm6l4OyXXvok6WckPeQAg=
